## configuration

# Site
title:                           Mambo Docs
subtitle:                        Mambo's development guide
author:                          Mambo
description:
language:                        ko
timezone:                        UTC

# URL
url:                             https://mambo-docs.github.io
root:                            /
permalink:                       :title/
permalink_defaults:

# Directory
source_dir:                      source
public_dir:                      public
archive_dir:                     archives
category_dir:                    categories
i18n_dir:                        :lang
tag_dir:                         tags
skip_render:                     [README.md, draft/**]

# Writing
default_layout:                  post
render_drafts:                   false
titlecase:                       true
external_link:                   true
post_asset_folder:               true
future:                          false

# Category & Tag
default_category:                uncategorized
category_map:
tag_map:

# Date / Time format
date_format:                     YYYY-MM-DD
time_format:                     HH:mm:ss

# Pagination
per_page:                        10
pagination_dir:                  page

deploy:
  type:                          git
  repo:                          https://__GITHUB_TOKEN__@github.com/mambo-docs/mambo-docs.github.io.git
  branch:                        master

article_emoji:
  full:                          true

browsersync:
  port: 14000
  ui: false

# https://futurecreator.github.io/2016/06/23/search-engine-optimization-hexo-plugins/
nofollow:
  enable:                        true

sitemap:
  path:                          sitemap.xml
  tag:                           false
  category:                      false

markdown: 'default'

highlight:
    enable: true
    line_number: false
    wrap: true
    hljs: false

index_generator:
  path:                      ''
  per_page:                  10
  order_by:                  -date

category_generator:
  per_page:                  10

archive_generator:
  enabled:                   false
  per_page:                  10
  yearly:                    true
  monthly:                   true
  daily:                     true
  order_by:                  -date

tag_generator:
  per_page: 10
  order_by: -date

theme: next
theme_config:
  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------
  menu:
    home: / || fas fa-home
    archives: /archives/ || fas fa-archive
    스프링 프레임워크 가이드: /categories/스프링-프레임워크-가이드/ || fas fa-book
    스프링 프레임워크 이야기: /categories/스프링-프레임워크-이야기/ || fas fa-book
    
  google_site_verification:        LMcddVW6xLBS7X1htGQ3duOIEmVp4ljku8sd3UuIcBg
  naver_site_verification:         967670e7891eb52e115709ce4890e2e8f576a1e5